### ISSUE TITLE
kspace_train

### ISSUE THREAD

**Issue by ZhengguoTan** [byaman14/SSDU#2]
Dear Dr. Yaman,

Thank you for the SSDU toolbox. 

I may have some questions with regard to 

https://github.com/byaman14/SSDU/blob/main/train.py#L43

For instance, I have such a file from fastMRI: file_brain_AXFLAIR_210_6001505.h5, whose shape is (16, 20, 640, 320). 16 is the number of slices, 20 is the number of coils, 640 is the number of readouts, and 320 is the phase encoding lines.

Does the "kspace_dir" file also have the same shape as the one above?

If so, then I don't understand in 

https://github.com/byaman14/SSDU/blob/main/masks/ssdu_masks.py#L35

why does it hold true for nrow, ncol = input_data.shape[0], input_data.shape[1]

To my understanding, input_data.shape[0] is the coil dimension, isn't it?

Best Regards,
Zhengguo

**Comment by byaman14** [comment]
Dear Zhengguo,

Thanks for pointing this out. The kspace and sensitivity maps should have size of nSlices x nrow x ncol x ncoil and mask should have size of nrow x ncol.  I have now updated `readme.md` file with this information. Hope this clarifies your questions. 

Kind regards,
Burhan

**Comment by ZhengguoTan** [comment]
Dear Burhan,

Thank you for your instruction. It helps!

Best Regards,
Zhengguo
