### ISSUE TITLE
Academic doubts

### ISSUE THREAD

**Issue by Dongq1qi** [byaman14/SSDU#5]
Hello, I am a student engaged in the field of artificial intelligence and medical technology research.
I'm copying this paper of yours about SSDU（[Self-Supervised Physics-Based Deep Learning MRI Reconstruction Without Fully-Sampled Data](https://paperswithcode.com/paper/self-supervised-physics-based-deep-learning)） right now.
I have already downloaded fastMRI data, but I don`t know which dataset you used in your paper. And I can`t find 'sense_map' in the dataset. One theory is that sensemap data needs to be modeled by myself, if it is ,how can I model it. If it not, where can I find it.
That`s really bother me, hope you can answer me? 
Thank you

**Comment by byaman14** [comment]
Hi,
Data: We have used fastmri dataset in our study. You can also use fastMRI data provided here  https://github.com/VLOGroup/mri-variationalnetwork  
Sensitivity maps: We have generated sensitivity maps using espirit method (more details are available in the paper). You can also use BART toolbox which I believe also uses the espirit method.
